WIP: OIDC integration for Vault

diff --git a/vault/helm/vault/templates/init-job.yaml b/vault/helm/vault/templates/init-job.yaml
--- a/vault/helm/vault/templates/init-job.yaml
+++ b/vault/helm/vault/templates/init-job.yaml
@@ -38,16 +38,25 @@ data:
     set -euo pipefail
 
     wait_for_pods() {
-        echo "Waiting for Vault pods to start..."
         timeout_s=300  # 5 minutes
+        echo "Waiting for Vault pods to start (timeout: $timeout_s s)"
         time_waiting_s=0
-        while ! kubectl -n vault get pod/vault-0 > /dev/null 2>&1; do
-            echo -n "."
-            sleep 20
-            time_waiting_s=$[ $time_waiting_s + 20 ]
-            if [ $time_waiting_s -ge $timeout_s ]; then
-                echo "ERROR: Vault pods did not start without $timeout_s seconds"
-                exit 1
+        started=no
+        while [ $started == no ]; do
+            set +e
+            # XXX
+            output=$(kubectl -n vault get pod/vault-0 -o jsonpath='{.status.phase}')
+            set -e
+            if [ "$output" == Running ]; then
+                started=yes
+            else
+                echo -n "."
+                sleep 20
+                time_waiting_s=$[ $time_waiting_s + 20 ]
+                if [ $time_waiting_s -ge $timeout_s ]; then
+                    echo "ERROR: Vault pods did not start without $timeout_s seconds"
+                    exit 1
+                fi
             fi
         done
         echo "I can see the Vault pods have started"
@@ -55,9 +64,9 @@ data:
 
     wait_for_pods
 
-    echo "Checking whether Vault is initialized or not..."
+    echo "Checking whether Vault is initialized or not"
     set +e
-    output=$(kubectl -n vault exec -it vault-0 -c vault -- vault status)
+    output=$(kubectl exec -n vault -it vault-0 -c vault -- vault status)
     set -e
     initialized=$(echo "$output" | awk '{ if ($1 == "Initialized") { print $2 } }')
     if [ "$initialized" == "true" ]; then
@@ -65,13 +74,45 @@ data:
         exit 0
     fi
 
-    echo "Initializing Vault..."
-    # TODO: hide the output of `vault operator init` because it contains secrets
-    kubectl -n vault exec -it vault-0 -c vault -- vault operator init
+    echo "Initializing Vault"
+    output=$(kubectl exec -n vault -it vault-0 -c vault -- vault operator init)
+    root_token=$(cat $output | grep '^Initial Root Token:' | awk '{ print $4 }')
 
-    echo "Restarting the Vault pods..."
+    echo "Restarting the Vault pods"
     kubectl delete -n vault -l app.kubernetes.io/instance=vault,component=server pod
     wait_for_pods
+
+    {{ if .Values.oidc_enabled }}
+    echo "Logging in with the root token"
+    kubectl exec -n vault -it vault-0 -c vault -- vault login "$root_token"
+
+    echo "Create plural policy, entity and alias"
+    kubectl exec -n vault -it vault-0 -c vault -- vault policy write plural - <<EOF
+    path "*" {
+      capabilities = ["list", "read", "create", "update", "patch", "delete", "sudo"]
+    }
+    EOF
+    output=$(kubectl exec -n vault -it vault-0 -c vault -- vault write identity/entity \
+        name=plural \
+        policies=plural)
+    entity_id=$(echo "$output" | awk '{ if ($1 == "id") { print $2 } }')
+    accessor=$(kubectl exec -n vault -it vault-0 -c vault -- vault auth list | awk '{ if ($1 == "oidc/") { print $3 } }')
+    kubectl exec -n vault -it vault-0 -c vault -- vault write identity/entity-alias \
+        name=plural \
+        mount_accessor="$accessor" \
+        canonical_id="$entity_id"
+
+    echo "Create plural role"
+    TODO NEXT from here: create role
+
+    echo "Enable and configure OIDC"
+    kubectl exec -n vault -it vault-0 -c vault -- vault auth enable oidc
+    kubectl exec -n vault -it vault-0 -c vault -- vault write auth/oidc/config \
+        oidc_discovery_url="{{ .Values.oidc_discovery_url }}" \
+        oidc_client_id="{{ .Values.oidc_client_id }}" \
+        oidc_client_secret="{{ .Values.oidc_client_secret }}" \
+        default_role=plural
+    {{ end }}
 ---
 apiVersion: batch/v1
 kind: Job
